version: '3.9'

services:

  joomla:
    image: docker.io/library/joomla-cluster
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 9090:80
      - 9191:443
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: example
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes: 
      - ./html:/var/www/html/

  joomladb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      